version: '3.3'
services:
  client:
        depends_on:
                - flask
        image: nginx:latest
        ports: 
                - "8900:80"
        volumes:
                - ./stock-prediction-app/build:/usr/share/nginx/html
  flask:
        build: flask-api
        ports:
        - "8009:8009"